### ISSUE TITLE
Documentation: Add YT-DL to official jellyfin/jellyfin image on deployment

### ISSUE THREAD

**Issue by pojlFDlxCOvZ4Kg8y1l4** [ankenyr/jellyfin-youtube-metadata-plugin#135]
Hello,

There are examples on how to install YT-DLP to a running container in the README. 
And to install YT-DLP to a LSIO Jellyfin docker container on deployment.
But a example for the official jellyfin docker container is missing.
I would like to add to the README a working inline dockerfile that adds YT-DLP to the [official jellyfin](https://hub.docker.com/r/jellyfin/jellyfin) docker image, not the one from [LSIO](https://docs.linuxserver.io/images/docker-jellyfin/#application-setup).
Navigating through Github is still a big mystery to me, I can't seem to figure out how to propose an updated README.
I have attached a log from the deployment. 
The plugin shows as active after redeploying a destroyed jellyfin container, and seems to be working as expected.

![Image](https://github.com/user-attachments/assets/6a114ce2-6cc7-4ed2-9c28-d569179d52e5)

The necessary build context for the README:

```
    build: 
      context: .
      no_cache: true
      pull: true
      dockerfile_inline: |
         FROM jellyfin/jellyfin
         RUN python3 -m pip install --user pipx
         RUN python3 -m pipx ensurepath
         RUN pipx ensurepath --global # optional to allow pipx actions with --global argument
         RUN pipx install yt-dlp
```

And as a full docker compose example, edited version from https://jellyfin.org/docs/general/installation/container :

```
services:
  jellyfin:
  #  image: jellyfin/jellyfin # image gets pulled within build context
    container_name: jellyfin
    user: UID:GID
    restart: unless-stopped
    network_mode: 'host'
    build: 
      context: .
      no_cache: true
      pull: true
      dockerfile_inline: |
         FROM jellyfin/jellyfin
         RUN python3 -m pip install --user pipx
         RUN python3 -m pipx ensurepath
         RUN pipx ensurepath --global # optional to allow pipx actions with --global argument
         RUN pipx install yt-dlp
    volumes:
      - /path/to/config:/config
      - /path/to/cache:/cache
      - type: bind
        source: /path/to/media
        target: /media
      - type: bind
        source: /path/to/media2
        target: /media2
        read_only: true
      # Optional - extra fonts to be used during transcoding with subtitle burn-in
      - type: bind
        source: /path/to/fonts
        target: /usr/local/share/fonts/custom
        read_only: true
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway' 
```

[deploy.log](https://github.com/user-attachments/files/19525948/deploy.log)
